// APP
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_SIGNED_IN = 'SET_SIGNED_IN';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_GAME = 'SET_GAME';
export const SET_LOADING = 'SET_LOADING';
export const SET_SERVER_CONNECTED = 'SET_SERVER_CONNECTED';
export const SET_SOCKETPROXY = 'SET_SOCKETPROXY';
export const SET_PLAYERS = 'SET_PLAYERS';

// CHAT
export const SET_MESSAGE_ERROR = 'SET_MESSAGE_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_MESSAGE_SENDING = 'SET_MESSAGE_SENDING';
export const SET_MESSAGE = 'SET_MESSAGE';
