// APP
export const SET_APP_NAME = 'SET_APP_NAME';
export const ON_USER_SIGN_IN = 'ON_USER_SIGN_IN';

// HOME
export const SET_HOME_TITLE = 'SET_HOME_TITLE';

// CANVAS
export const SET_CANVAS_WIDTH = 'SET_CANVAS_WIDTH';
export const SET_CANVAS_HEIGHT = 'SET_CANVAS_HEIGHT';
export const SET_MODEL_COORDINATES = 'SET_MODEL_COORDINATES';
export const SET_DRAGGING = 'SET_DRAGGING';
export const ON_MODEL_SELECT = 'ON_MODEL_SELECT';
