// APP
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_SIGNED_IN = 'SET_SIGNED_IN';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_GAME = 'SET_GAME';
export const SET_LOADING = 'SET_LOADING';
export const SET_SERVER_CONNECTED = 'SET_SERVER_CONNECTED';
